import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import StoreProvider from "./components/StoreProvider";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import CartProviderWrapper from "./components/CartProviderWrapper";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<SessionProviderWrapper>
					<StoreProvider>
						<CartProviderWrapper>
							<Nav />
							{children}
						</CartProviderWrapper>
					</StoreProvider>
				</SessionProviderWrapper>
			</body>
		</html>
	);
}
